# Imported from Kasumi e648702b42d6068206a5cbc2fffae25d71dc067b.
kernelsu-objs += $(addprefix kasumi/, \
 core/kasumi_bootstrap.o core/kasumi_config_guard.o \
 core/kasumi_runtime.o core/kasumi_fop_bridge.o \
 core/kasumi_vnode.o core/kasumi_dirhijack.o core/kasumi_sop_shadow.o \
 core/kasumi_hide_events.o core/kasumi_hide_rules.o \
 control/kasumi_ioctl.o \
 policy/kasumi_path_policy.o overlay/kasumi_overlay.o \
 hooks/kasumi_proc_read_hooks.o \
 hooks/kasumi_vfs_hooks.o \
 features/kasumi_iop_override.o \
 features/kasumi_fop_override.o features/kasumi_fake_mountinfo.o \
 features/kasumi_vfs_view.o)
ccflags-y += -DKASUMI_EMBEDDED
ccflags-y += -I$(srctree)
ccflags-y += $(addprefix -I$(MDIR)/kasumi/,include internal core control policy overlay hooks features)
